### ISSUE TITLE
[Bug] LightGBM error while using early stopping

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/tune-sklearn#115]
I'm getting the following error while setting `early_stopping=True` in `TuneSearchCV` where `estimator = LGBMClassifier(early_stopping_rounds=50)` :

`ValueError: For early stopping, at least one dataset and eval metric is required for evaluation`

The same works fine for XGBoost. A couple of related questions:
1. Why isn't it mandatory for the user to set `early_stopping_rounds` within the estimator while setting `early_stopping=True`?
2. Still not sure how `max_iters` comes into play. When I set `n_trials=10` and `max_iters=10`, it seems to be running 100 trials anyway. How is the early_stopping happening?
3. Isn't it better to merge `early_stopping` and `early_stopping_rounds` like how it is done in [LightGBMTunerCV](https://github.com/optuna/optuna/blob/master/optuna/integration/_lightgbm_tuner/optimize.py)?
4. If another level of early stopping has to be implemented across trials (mentioned [here](https://github.com/ray-project/tune-sklearn/issues/98)), will the same ASHA scheduler work?

**Comment by richardliaw** [comment]
cc @Yard1 ?

**Comment by Yard1** [comment]
I think it's not something we can influence, as this is early stopping inside LightGBM itself. Our early stopping is implemented on top of early stopping that may be inside estimators themselves. Are you using the release version or the master branch? LightGBM early stopping is not present in the former IIRC. I followed the logic @inventormc implemented for xgboost, they may have a better idea about the details.

**Comment by rohan-gt** [comment]
@Yard1 @inventormc can you provide a tune_sklearn code example using early stopping with XGBoost, LightGBM and CatBoost? Is it possible to set `early_stopping_rounds`? If not, how is the early stopping implemented?
