### ISSUE TITLE
Feature Request: Support unified search space

### ISSUE THREAD

**Issue by richardliaw** [ray-project/tune-sklearn#124]
Tune now has a unified search space on 1.0; tune-sklearn should support that space too.

**Comment by Yard1** [comment]
@richardliaw Does it mean we should get rid of the automatic conversion from `dict` to algo specific search space, and instead convert `dict`s to tune's unified search space and then pass it to the algos? Leaving already converted search spaces as-is, of course.

**Comment by richardliaw** [comment]
Hmm, possible to leave that as-is. The issue is so that users can pass in their search space in the Tune API format.

**Comment by Yard1** [comment]
Adding just that should be a quick and easy change. Just to be certain - we don't need to do any processing of it here, do we? I took a look at Tune code and it seems like it's all handled within the algos themselves.

**Comment by richardliaw** [comment]
yep! all is done in tune

**Comment by Yard1** [comment]
Happy to work on this, then.

**Comment by richardliaw** [comment]
Great! I'll assign this to you, and just cc @krfricke when you're done!

**Comment by richardliaw** [comment]
Awesome! This should be addressed with the new release :)
