### ISSUE TITLE
[Issue] TypeError: init() got an unexpected keyword argument 'include_dashboard'

### ISSUE THREAD

**Issue by vectosaurus** [ray-project/tune-sklearn#155]
Running the hyperopt example for `TuneSearchCV`  from the readme page yields the following error

```TypeError: init() got an unexpected keyword argument 'include_dashboard'```

This is the code I am running. I face the same issue with the `'bayesian'` optimization too. How to fix this?

```

import scipy
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
X, y = make_classification(n_samples=11000, n_features=1000, n_informative=50, n_redundant=0, n_classes=10, class_sep=2.5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1000)

param_dists = {
    'alpha': (1e-4, 1e-1),
    'epsilon': (1e-2, 1e-1)
}

hyperopt_tune_search = TuneSearchCV(SGDClassifier(),
    param_distributions=param_dists,
    n_trials=2,
    early_stopping=True, # uses Async HyperBand if set to True
    max_iters=10,
    search_optimization="hyperopt"
)

hyperopt_tune_search.fit(X_train, y_train)
```

**Comment by Yard1** [comment]
Does this issue persist on the master branch version of tune-sklearn?

**Comment by vectosaurus** [comment]
Yes, I've installed the library using pip. I am not using any other branches

**Comment by Yard1** [comment]
Could you try `pip install -U git+https://github.com/ray-project/tune-sklearn.git`? This will install the development version of tune-sklearn. If the issue still persists after that, try updating your Ray package.

**Comment by vectosaurus** [comment]
@Yard1 

I tried the install you provided but got the following error 

```ImportError: cannot import name 'Domain' from 'ray.tune.sample' (/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/sample.py)```

The command you gave installs `tune-sklearn-0.0.8` so I went ahead and upgraded to `tune-sklearn-0.1.0`. Doing that now gives me the following error

```TypeError: __init__() got an unexpected keyword argument 'sk_n_jobs'```

**Comment by vectosaurus** [comment]
@Yard1 

I tried the install you provided but got the following error 

```ImportError: cannot import name 'Domain' from 'ray.tune.sample' (/home/ubuntu/anaconda3/lib/python3.7/site-packages/ray/tune/sample.py)```

The command you gave installs `tune-sklearn-0.0.8` so I went ahead and upgraded to `tune-sklearn-0.1.0`. Doing that now gives me the following error

```TypeError: __init__() got an unexpected keyword argument 'sk_n_jobs'```

**Comment by Yard1** [comment]
The version number is a mistake on our part, the code I gave you will install the latest version of the package, consistent with the master branch of this repository.

You should update your Ray install.

```
pip uninstall ray tune-sklearn
pip install -U ray[tune]
pip install -U git+https://github.com/ray-project/tune-sklearn.git
```

This should work. Let me know how it goes.

**Comment by vectosaurus** [comment]
I tried the steps above, I am getting the same error- 

```TypeError: __init__() got an unexpected keyword argument 'sk_n_jobs'```

I am using the example from [here](https://github.com/ray-project/tune-sklearn#tunesearchcv)

**Comment by Yard1** [comment]
Can you try creating a new conda/virtualenv environment and running the commands I posted again? There seems to be an issue with packages you have installed.

**Comment by vectosaurus** [comment]
@Yard1 

This works with venv now. Thanks a lot for the inputs. 

Could also you point me to the documentation that says how to handle Integer or Categorical hyperparams?

Thanks again

**Comment by Yard1** [comment]
You can use tune's search spaces for all algorithms - https://docs.ray.io/en/master/tune/tutorials/overview.html#how-do-i-choose-hyperparameter-ranges. Just pass the config dict as `param_distributions` argument.

You can pass the fit arguments through the `fit` method of `TuneSearchCV`, eg.
```python
hyperopt_tune_search.fit(X, y, my_fit_param="a")
```

**Comment by vectosaurus** [comment]
Thanks a lot @Yard1
