### ISSUE TITLE
Upload source dist to pypi for conda package

### ISSUE THREAD

**Issue by hadim** [ray-project/tune-sklearn#159]
The pypi build only contains a wheel. It would be nice to have a source package for packaging on conda forge: https://pypi.org/project/tune-sklearn/#files

**Comment by richardliaw** [comment]
Oh nice -- @hadim did you already get to this?

**Comment by hadim** [comment]
Yup, it's there already https://github.com/conda-forge/tune-sklearn-feedstock/blob/master/recipe/meta.yaml#L9

**Comment by richardliaw** [comment]
Awesome, I wish I could send you a coffee for this! Thanks a bunch!

**Comment by hadim** [comment]
Thanks.

The package is here indeed but it relies on the git release archive. It is preferred on conda forge to rely on the source archive from pypi. Could you upload it for the next release? Currently pypi only contains the wheel archive.
