### ISSUE TITLE
RuntimeError: Unable to connect to Redis at 127.0.0.1:6379.

### ISSUE THREAD

**Issue by Weidong725** [ray-project/tune-sklearn#172]
This error occurs when I run the sample file of random forest，How can I solve it？

**Comment by richardliaw** [comment]
@Weidong725 can you post the entire stacktrace?

**Comment by mkretsch327** [comment]
@Weidong725 - If this is still an issue I'd check your VPN/firewall settings, I've received this error when on a restrictive VPN. A full stacktrace would be most helpful though.
