### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by theshy456** [ray-project/tune-sklearn#174]
AttributeError: partially initialized module 'ray' has no attribute 'compat' (most likely due to a circular import)
![微信图片_20210106234706](https://user-images.githubusercontent.com/63041101/103788185-85252100-5079-11eb-9849-c26b1d1d621d.jpg)

**Comment by Yard1** [comment]
Try installing ray and tune-sklearn in a new virtualenv.

**Comment by theshy456** [comment]
A new vitualenv?

**Comment by theshy456** [comment]
> Try installing ray and tune-sklearn in a new virtualenv.
Answer else?

**Comment by theshy456** [comment]
> Try installing ray and tune-sklearn in a new virt

**Comment by theshy456** [comment]
> Try installing ray and tune-sklearn in a new virtualenv.


![Uploading 微信图片_20210107005207.jpg…]()

**Comment by theshy456** [comment]
> 尝试在新的virtualenv中安装ray和tune-sklearn。

![微信图片_20210107005207](https://user-images.githubusercontent.com/63041101/103796916-c4a43b00-5082-11eb-8992-0a6cf41476a4.jpg)

**Comment by theshy456** [comment]
> 尝试在新的virtualenv中安装ray和tune-s

**Comment by richardliaw** [comment]
Please post this issue on https://github.com/ray-project/ray as it seems unrelated to tune-sklearn specifically!
