### ISSUE TITLE
[feature] Support any Searcher/Stopper in Tune

### ISSUE THREAD

**Issue by Yard1** [ray-project/tune-sklearn#187]
The user should be able to pass a Searcher/Stopper object in addition to predefined strings in `TuneSearchCV`. It would be quite easy to add support for that, however first the search space conversions in tune-sklearn need to be unified as to either convert the objects that can be passed right now to Tune search spaces (which will then get converted to Searcher-specific spaces inside those) or make an API breaking change and allow only Tune search spaces + whatever can be passed to sklearn's `GridSearchCV`.

**Comment by Yard1** [comment]
@richardliaw

**Comment by richardliaw** [comment]
Fixed with #198
