### ISSUE TITLE
TuneBaseSearchCV to extend BaseSearchCV from sklearn

### ISSUE THREAD

**Issue by Matgrb** [ray-project/tune-sklearn#193]
Currently, the TuneBaseSearchCV inherits from BaseEstimator from sklearn, however, I suppose it should extend BaseSearchCV, in order to be fully consistent with the sklearn API. Thanks to this one can detect, whether this object is in fact an optimization search schema, or a classifier.

**Comment by Yard1** [comment]
Will be covered by https://github.com/ray-project/tune-sklearn/pull/192
