### ISSUE TITLE
TuneSearchCV not Working [tune]

### ISSUE THREAD

**Issue by abheesht17** [ray-project/tune-sklearn#195]
### What is the problem?
Consider this piece of code:
```
from ray.tune.sklearn import TuneSearchCV
from sklearn.linear_model import SGDClassifier
from sklearn import datasets
from sklearn.model_selection import train_test_split
import numpy as np

digits = datasets.load_digits()
x = digits.data
y = digits.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2)

clf = SGDClassifier()
parameter_grid = {"alpha": (1e-4, 1), "epsilon": (0.01, 0.1)}

tune_search = TuneSearchCV(
    clf,
    parameter_grid,
    search_optimization="bayesian",
    n_trials=3,
    early_stopping=True,
    max_iters=10,
)
tune_search.fit(x_train, y_train)
print(tune_search.best_params_)
```
This has been obtained from the [docs](https://docs.ray.io/en/master/tune/tutorials/tune-sklearn.html#using-bayesian-optimization).
I am running the code on Colab. I have reproduced the error on the following link:
https://colab.research.google.com/drive/1z2vpBE7HTS6Iq2G_h9MQWIL_Aw8pKzaT?usp=sharing

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

**Comment by richardliaw** [comment]
This just requires a better error message on our side. Please run `pip install tune_sklearn`.

**Comment by abheesht17** [comment]
Thank you for the swift reply! It works now.
