### ISSUE TITLE
Use `ray.put` for shared memory

### ISSUE THREAD

**Issue by richardliaw** [ray-project/tune-sklearn#2]
Right now, we do N transfers of the same data object. It would be nice to avoid doing that by using the shared memory object store via `ray.put`

```
object_id = ray.put(X)

class SKLTrainable(tune.Trainable):
    def _setup(self, config):
        object_id = config["data"]
        new_X = ray.get(object_id)


tune.run(SKLTrainable, config={"data": object_id})
```

**Comment by anthonyhsyu** [comment]
Closed in a previous commit. In the future we will take note and close this via commit.
