### ISSUE TITLE
Does HEBOSearch work in tune-sklearn?

### ISSUE THREAD

**Issue by qo4on** [ray-project/tune-sklearn#203]
Setting `search_optimization=HEBOSearch()` returns an error in [your example](https://github.com/ray-project/tune-sklearn/blob/7f4b33b9fbfb5429898701282ec6feff4165ae39/examples/discrete_hyperopt.py).

**Comment by Yard1** [comment]
There's only support for some searchers built into tune-sklearn - I've got a PR (https://github.com/ray-project/tune-sklearn/pull/198) to allow it to use any searcher in Ray but there are some design issues that need to be resolved.
