### ISSUE TITLE
ValueError: Tune-sklearn no longer supports nested parallelism with new versions of joblib/sklearn. Don't set 'sk_n_jobs'.

### ISSUE THREAD

**Issue by RNarayan73** [ray-project/tune-sklearn#221]
Hello,

I'm trying to use TuneSearchCV in a pipeline nested within the cross_validate function. As per sklearn's [recommendation](https://scikit-learn.org/stable/auto_examples/model_selection/plot_nested_cross_validation_iris.html#sphx-glr-auto-examples-model-selection-plot-nested-cross-validation-iris-py) this will enable a more robust evaluation of the generalisation error. Note, this isn't a cross validation for hyperparameter optimisation within TuneSearchCV, but of the overall pipeline which includes TuneSearchCV as the last step.
![image](https://user-images.githubusercontent.com/82275999/134586169-99f60731-161a-447f-aa3e-e1878cad6c49.png)

I get the above error when I execute cross_validate even though sk_n_jobs is left as the default value (None). 
Furthermore, when I explicitly set sk_n_jobs to 1 (in the hope of avoiding parallelism) I get the same error earlier, when I try to instantiate TuneSearchCV.

How can I avoid this and run cross_validation? I have managed to test models this way using GridSearchCV and the SKOpt, Optuna optimisers with their SKLearn wrapper, but am stuck when trying it with TuneSearchCV.

Thanks for your help.

Narayan

**Comment by Yard1** [comment]
Are you using the latest release of tune-sklearn (0.4.1)?

**Comment by RNarayan73** [comment]
Yes, on 0.4.1
Here's the code:
`hpt_pipe = TuneSearchCV(pipe, 
                                param_distributions=get_params_space(algo, hpt), 
                                cv=cv_skf,   # cv object
                                scoring=score_metrics,    # dict with scoring metrics
                                refit=eval_metric, 
                                name=hpt + '-' + run, 
                                #early_stopping=False, 
                                pipeline_auto_early_stop=True,  # If True, early stopping will be performed on the last stage of the pipeline (which must support early stopping)
                                                                # If False, early stopping will be determined by ‘Pipeline.warm_start’ or ‘Pipeline.partial_fit’ capabilities, which are by default not supported by standard SKlearn
                                local_dir=TUNE_FOLDER, 
                                n_trials=ITERS, random_state=SEED, 
                                #sk_n_jobs=None,   # Tune-sklearn no longer supports nested parallelism with new versions of joblib/sklearn. Don't set 'sk_n_jobs'
                                n_jobs=JOBS, verbose=1, 
                                **kwargs,
                               )`
The above pipeline works fine when I run it through a standard train-test-split validation.

Hope this helps

Narayan

**Comment by Yard1** [comment]
Is it possible that `sk_n_jobs` is somehow passed through kwargs?

**Comment by RNarayan73** [comment]
Unlikely, 
Here's the call to a helper function get_pipe that returns a pipeline for an algorithm and HP tuning (*SearchCV) method within which contains the above code.
`tune_pipe, _ = get_pipe(algo=ALGO, hpt=HPT, val=VAL, score_metrics=score_metrics, eval_metric=eval_metric, 
                        mem=mem, run=RUN, persist=PERSIST, search_optimization=search, early_stopping=early) #TUNE_SEARCH[search_algo])`

Here's the values for the HPs that I get by running tune_pipe.get_params()
{'cv': StratifiedKFold(n_splits=5, random_state=0, shuffle=True),
 'early_stopping': False,
 'error_score': nan,
 *** estimator parameters truncated here ***
  'local_dir': './_tune/',
 'loggers': [ray.tune.logger.JsonLogger, ray.tune.logger.CSVLogger],
 'max_iters': 1,
 'mode': 'max',
 'n_jobs': -1,
 'n_trials': 50,
 'name': 'tune-setup',
 'param_distributions': {'clf__alpha': <ray.tune.sample.Float at 0x200ad96dd00>},
 'pipeline_auto_early_stop': True,
 'random_state': 0,
 'refit': 'avg_prec',
 'return_train_score': False,
 'scoring': {'profit_ratio': make_scorer(profit_ratio_score),
  'precision': make_scorer(precision_score, average=binary),
  'f_0.5': make_scorer(fbeta_score, beta=0.5, pos_label=1),
  'avg_prec': make_scorer(average_precision_score, needs_proba=True, pos_label=1),
  'brier_rel': make_scorer(brier_rel_score, needs_proba=True, pos_label=1)},
 'search_optimization': 'bayesian',
 'sk_n_jobs': 1,
 'stopper': None,
 'time_budget_s': None,
 'use_gpu': False,
 'verbose': 1}

**Comment by Yard1** [comment]
`'sk_n_jobs': 1,` is there. Can you remove it?

**Comment by RNarayan73** [comment]
No, I can't. 
It seems the sk_n_jobs default value of 'None' is being translated as 1 during initialisation, even though I don't explicitly assign it any value. Notice it is commented out when initialising TuneSearchCV. The error comes up when I try to run cross_validate.
If I try to explicitly set it to 1, then the error occurs earlier, when initialising TuneSearchCV.

**Comment by Yard1** [comment]
Could you install `pip install git+https://github.com/Yard1/tune-sklearn.git@fix_sk_n_jobs` and try again?

**Comment by RNarayan73** [comment]
Good!
That resolved the sk_n_jobs issue. 

However, now I get another error:
RuntimeError: Cannot clone object TuneSearchCV(cv=StratifiedKFold(n_splits=5, random_state=0, shuffle=True),
             early_stopping=False,
             estimator=Pipeline(steps=[('enc',
                                        ColumnTransformer(sparse_threshold=0,
                                                          transformers=[('drop',
                                                                         'drop',
                                                                         ['WeekBegin',
                                                                          'AutoML_split']),
                                                                        ('numeric',
                                                                         'passthrough',
                                                                         ['RSI',
                                                                          'h1RSI',
                                                                          'h2RSI']),
                                                                        ('target',
                                                                         MEstimateEncoder(random_state=0),
                                                                         ['SignalTime',
                                                                          'Symbol',
                                                                          'CandleType'...
             random_state=0, refit='avg_prec',
             scoring={'avg_prec': make_scorer(average_precision_score, needs_proba=True, pos_label=1),
                      'brier_rel': make_scorer(brier_rel_score, needs_proba=True, pos_label=1),
                      'f_0.5': make_scorer(fbeta_score, beta=0.5, pos_label=1),
                      'precision': make_scorer(precision_score, average=binary),
                      'profit_ratio': make_scorer(profit_ratio_score)},
             sk_n_jobs=1, verbose=1), as the constructor either does not set or modifies parameter loggers

Should I raise another issue?

Thanks
Narayan

**Comment by Yard1** [comment]
I will look into it, thanks! This issue is fine

**Comment by RNarayan73** [comment]
Thank you very much, @Yard1. I look forward to your fix.

Narayan

**Comment by Yard1** [comment]
Sorry, I have been occupied with other matters. I'll get back to tune-sklearn issues this week. Will keep you updated!

**Comment by RNarayan73** [comment]
Hi @Yard1 
I tried this new version and the same error persists:
"RuntimeError: Cannot clone object TuneSearchCV(...), as the constructor either does not set or modifies parameter loggers"
Narayan

**Comment by RNarayan73** [comment]
That worked! Well done, @Yard1 
Are you intending to include this in the next release?
Thanks
Narayan

**Comment by Yard1** [comment]
Will look into it, thanks!

**Comment by Yard1** [comment]
There is an environment variable responsible for the directory name length, `TUNE_MAX_LEN_IDENTIFIER`. By default it is set to 130, but the entire path may be too long. Can you set that env var to a smaller number and see if that helps?

**Comment by RNarayan73** [comment]
@Yard1 
That's fine. Let me know if you have an update? I'd be happy to help with testing it.
Regards
Narayan

**Comment by Yard1** [comment]
Hey, sorry for delay. I am hoping to take a look at this this week.

**Comment by Yard1** [comment]
@RNarayan73 Sorry for taking so long. I have opened a PR to fix this. You can test it by `pip uninstall -y tune-sklearn && pip install -U git+https://github.com/Yard1/tune-sklearn.git@fix_early_stopping_cloning`

**Comment by RNarayan73** [comment]
@Yard1
Thanks for the udpate. I'm getting back in after a break. 

I saw #229 and noted that `fix_early_stopping_cloning ` has been deleted and merged into `ray-project:master`

So, I'm guessing that the install command is now `pip uninstall -y tune-sklearn && pip install -U git+https://github.com/ray-project/tune-sklearn.git@master`

Regards
Narayan

**Comment by Yard1** [comment]
Yes, that would be it :) @RNarayan73
