### ISSUE TITLE
error when using multimetric scoring with refit=False

### ISSUE THREAD

**Issue by yonil7** [ray-project/tune-sklearn#230]
https://github.com/ray-project/tune-sklearn/blob/1c6909223b2e892e97a07151f14d19b80bbffad4/tune_sklearn/tune_basesearch.py#L486
``` python
        if self._is_multi:
            if not isinstance(self.refit,
                              str) or self.refit not in self.scoring_:
                raise ValueError("When using multimetric scoring, refit "
                                 "must be the name of the scorer used to "
                                 "pick the best parameters.")
```

This code should check that `self.refit` is not set to `False` before raising an error

**Comment by Yard1** [comment]
This is intended, `refit` is required to specify which metric should be optimized for.
