### ISSUE TITLE
[Feature request] Early stopping doesn't work with XGBoost, LightGBM or CatBoost

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/tune-sklearn#58]
I'm getting the following error while setting `early_stopping=True`

    ValueError: Early stopping is not supported because the estimator does not have `partial_fit`

These could be a potential fixes:
1. XGBoost: https://github.com/dmlc/xgboost/issues/1686
2. LightGBM: https://github.com/microsoft/LightGBM/issues/2718
3. CatBoost: https://github.com/catboost/catboost/issues/464

**Comment by richardliaw** [comment]
Yeah, that's a good point. I think we'll probably want to special-case a training call for xgboost, lightgbm as they have a different way of doing early stopping..

**Comment by rohan-gt** [comment]
@richardliaw I've updated the issue with more details. Btw how does `max_iters` perform early stopping? I'm a little confused about how it works in conjunction with `n_iter`

**Comment by richardliaw** [comment]
yeah... i guess that's the penalty we have to pay for adhering to the sklearn API. 

max_iters = number of "epochs"
n_iter = number of hyperparameter evals.

Does that make sense?

**Comment by rohan-gt** [comment]
@richardliaw According to my understanding if I set `n_iter=10` and `max_iter=5` a minimum of 5 and a maximum of 10 iterations of a model are run right? So what's the early stopping condition that will stop the process after 5 iterations?

**Comment by richardliaw** [comment]
In #63, we're going to enable early stopping for XGBoost via incremental learning. We decided not to implement it for lgbm because it is not yet on a stable version.

**Comment by richardliaw** [comment]
Hmm, not sure how we're going to support CatBoost but will open an issue to track lightgbm.

**Comment by rohan-gt** [comment]
@richardliaw is early stopping enabled using cross-validation like I mentioned [here](https://github.com/ray-project/ray/issues/10163#issuecomment-683639094)? Because CatBoost has a `cv()` method too
