### ISSUE TITLE
[Enhancement] Smart error handling and hyperparameter resampling

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/tune-sklearn#65]
I'm trying out Bayesian optimization but the tuning errors out whenever an incompatible combination of hyperparameters occur. For example if I provide the following `param_diststributions` for `LogisticRegression`:

1. penalty: [‘l1’, ‘l2’, ‘elasticnet’]
2. solver: [‘newton-cg’, ‘lbfgs’, ‘liblinear’, ‘sag’, ‘saga’]

it throws an error because `elasticnet` is only supported by the `saga` solver and all other combinations are invalid. Is there a way to ignore such cases and just proceed with the tuning by resampling the hyperparameters?

**Comment by richardliaw** [comment]
Thanks for opening this @rohan-gt! Would it be OK if we proceeded with tuning without resampling?

**Comment by rohan-gt** [comment]
@richardliaw in TuneSearchCV, `n_iter` is the total number of trials and `max_iters` the early stopping for the same right? Without resampling won't the trails reduce drastically especially in a case like if 7/10 or even 10/10 cases error out?

**Comment by richardliaw** [comment]
Hmm... right. Would conditional search spaces (like HyperOpt or Optuna) work for you?

**Comment by rohan-gt** [comment]
@richardliaw Yes that could actually work

**Comment by richardliaw** [comment]
IIRC Tree-Parzen Estimators (which is the algorithm that optuna implements) shouldn't be much different to standard Bayesian Optimization (that skopt provides).

**Comment by rohan-gt** [comment]
Yes but scikit-optimize isn't an active project and throws errors with the latest scikt-learn

**Comment by richardliaw** [comment]
I think this is addressed with hyperopt thanks to #68!
