### ISSUE TITLE
[Feature Request] Add default model parameters to tuning trials

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/tune-sklearn#73]
While testing on multiple datasets I've observed that if `n_iter` is low, the tuned model has lower performance for both train and test sets compared to the model using default parameters. Is there a way to ensure that the default parameters of a model are tried out as the first trial and it starts optimizing from there? If there's no improvement, there's no need to run all the trials

**Comment by richardliaw** [comment]
Do you see the same behavior on RandomizedSearchCV?

**Comment by rohan-gt** [comment]
No. Only on Bayesian and others

**Comment by richardliaw** [comment]
@rohan-gt we can prioritize this in the upcoming week. thanks!

**Comment by rohan-gt** [comment]
One possible solution could be if the user sets 10 trials, the first one could be using the algorithm's default parameters and the rest 9 could be sampled randomly and progress from there

**Comment by Yard1** [comment]
Or the defaults could just be ran first, always - that way we guarantee the tuned model will not be worse than the one that went in.

**Comment by richardliaw** [comment]
What you want to do here is to implement something like Scikit-Optimize, where you can specify x0 and y0 upfront:

https://scikit-optimize.github.io/stable/modules/generated/skopt.optimizer.gbrt_minimize.html#skopt.optimizer.gbrt_minimize

**Comment by Yard1** [comment]
This probably needs to be handled outside the main optimization loop as it would be hard to just drop in the current model params into distributions (though it wouldn't be an issue with random/grid search).
